---
language: node_js
os: linux
dist: xenial
node_js:
  - lts/*
cache:
  directories:
    - node_modules
    - packages/icons/node_modules
    - packages/web/node_modules
    - packages/styles/node_modules
    - packages/docs/node_modules
  yarn:
    true
git:
  quiet: true
branches:
  except:
    - /v\d+\.\d+\.\d+$/
    - /v\d+\.\d+\.\d+-docs$/
jobs:
  include:
    - stage: confidence-check
      if: NOT (branch =~ /^DSY-(\d+)$/ OR branch = main)
      name: "Confidence check"
      script: yarn test:ci
    - stage: pre-release
      name: "Pre-release"
      if: type = push AND branch =~ /^DSY-(\d+)$/
      before_script:
        - "sh ./scripts/configure-git.sh"
        - "yarn lerna:prerelease:version:ci --preid alpha.$TRAVIS_BRANCH.$TRAVIS_BUILD_NUMBER"
      script: "yarn lerna:prerelease:publish:ci --pre-dist-tag $TRAVIS_BRANCH"
      after_script:
        - "chmod +x ./scripts/build-storybook.sh"
        - "sh ./scripts/build-storybook.sh"
    - stage: release
      name: "Release"
      if: type = push AND branch = main
      script: skip
      before_deploy:
        - "sh ./scripts/configure-git.sh"
        - "yarn lerna:release:version:ci"
      deploy:
        - provider: script
          script: "yarn lerna:release:publish:ci"
          skip_cleanup: true
          on:
            branch: main
      after_deploy:
        - "cd ${TRAVIS_BUILD_DIR}/packages/web"
        - "npx chromatic --exit-once-uploaded --project-token=$CHROMATIC_PROJECT_TOKEN"
